package util;

import java.io.Serial;
import java.io.Serializable;

/* Taken from tomte */
public class Tuple2<T0,T1> implements Serializable {
	@Serial
    private static final long serialVersionUID = 7482940805458320647L;
	public T0 tuple0;
	public T1 tuple1;

    public Tuple2(T0 tuple0,T1 tuple1){
		 this.tuple0 = tuple0;
		 this.tuple1 = tuple1;
	}

	public String toString(){
		return "(" + this.tuple0.toString() + "," + this.tuple1.toString()  + ")";
	}

	// generated by eclipse
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((tuple0 == null) ? 0 : tuple0.hashCode());
		result = prime * result + ((tuple1 == null) ? 0 : tuple1.hashCode());
		return result;
	}

	// generated by eclipse
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Tuple2<?, ?> other = (Tuple2<?, ?>) obj;
		if (tuple0 == null) {
			if (other.tuple0 != null)
				return false;
		} else if (!tuple0.equals(other.tuple0))
			return false;
		if (tuple1 == null) {
            return other.tuple1 == null;
		} else return tuple1.equals(other.tuple1);
    }
}

